[workspace]
members = [
    "crates/mt-rt"
    ]
resolver = "3"

[workspace.package]
edition = "2024"
rust-version = "1.90.0"
include = [
]

[workspace.dependencies]
cortex-m = "*"
cortex-m-rt = "*"
panic-halt = "*"
nrf52840-hal = "*"
embedded-hal = "*"
